const enMessages = {
    '_home.checkin.header': 'Check in',
    '_home.checkout.header': 'Check out',
    '_app.back': 'Back',
    '_app.next': 'NEXT',
    '_app.home': 'Start again',
    '_checkin.size.title': 'Locker size',
    '_checkin.time.title': 'Storage time',
    '_checkin.time.1': 'hour',
    '_checkin.time.1.s': 'hours',
    '_checkin.time.2': 'week',
    '_checkin.time.2.s': 'weeks',
    '_checkin.time.3': 'minute',
    '_checkin.time.3.s': 'minutes',
    '_checkin.time.4': 'day',
    '_checkin.time.4.s': 'days',
    '_checkin.endtime': 'Pick-up time',
    '_checkin.total': 'Total',
    '_checkin.summary': 'Summary',
    '_checkin.size': 'Locker size',
    '_checkin.time': 'Storage time',
    '_app.progress.select': 'Select',
    '_app.progress.review': 'Review',
    '_app.progress.payment': 'Payment',
    '_app.progress.success': 'Success',
    '_app.homemodalbody': 'You will have to re-enter your data if you navigate back to the home screen.',
    '_app.cancel': 'Cancel',
    '_review.summary': 'Your locker details.',
    '_review.info': 'Important information',
    '_review.acceptlabel': 'I accept the AirSpace',
    '_review.acceptlabel.2': 'Terms and Conditions',
    '_review.overtime.info': 'You will have to pay an overtime storage fee if you fail to retrieve your belongs by the appointed pick-up time!',
    '_review.acceptlink': 'Read the Terms and Conditions',
    '_review.checkboxmodal.title': 'To proceed, you must first accept the AirSpace',
    '_app.creditcard.error': 'It is not possible to make a payment or reservation via the terminal at this time. Please use the Airspace phone app to complete these functions. You can check in, however, if you already have a booking.',
    '_app.no_config_data': 'Due to a system failure, you have been navigated back to the home screen. We apologize for the inconvenience. ',
    '_checkin.changed.availabilities': 'This locker size is currently not available. Try choosing another locker size, or please check back with us later.',
    '_app.no_session': 'Due to a system failure, you have been navigated back to the home screen. We apologize for the inconvenience. ',
    '_app.no_required_data': 'Due to a system failure, you have been navigated back to the home screen. We apologize for the inconvenience. ',
    '_payment.failed': 'This transaction has been declined.',
    '_app.retrybutton': 'Try this again',
    '_review.backnavigate': 'Would you like to navigate back to the previous screen?',
    '_payment.title': 'Please swipe or insert your card for payment.',
    '_payment.accept': 'We accept',
    '_payment.security': '100% SECURE PAYMENT',
    '_payment.processing': 'Processing...',
    '_payment.success': 'Payment success!',
    '_payment.openlocker': 'OPEN MY LOCKER',
    '_payment.warning': 'Please keep this receipt! It contains all your locker-related info, including the 6-digit PIN needed to open your locker when you return to pick up your luggage!',
    '_payment.printing': 'Printing... Please wait.',
    '_payment.printing.ready': 'Ready! Please take your receipt!',
    '_payment.locker': 'This is your locker number:',
    '_payment.printer.fail': 'We can\'t print your locker information right now. Please write down your PIN and locker number below. We apologize for the inconvenience.',
    '_payment.pin': 'PIN:',
    '_payment.locker.number': 'Locker number:',
    '_thankyou.lockerfailed': 'It seems that there\'s a problem with opening your locker. Please ask a staff member for assistance!',
    '_thankyou.thankyou': 'Thank you!',
    '_success.lockernumber.text': 'Locker number',
    '_thankyou.open': 'is opened for you!',
    '_thankyou.keep': 'KEEP YOUR RECEIPT!',
    '_thankyou.keep.2': 'Use the 6-digit PIN printed on your receipt to open your locker.',
    '_thankyou.enjoy': 'Please enjoy your stay in',
    'Budapest': 'Budapest!',
    '_thankyou.next': 'Next customer',
    'right': 'Find it on your right',
    'left': 'Find it on your left',
    'front': 'Find it in front of you',
    'behind': 'Find it behind you',
    '_checkout.info': 'You will \"check out\" if you open your locker at this time, and will not be able to lock it again without paying for a new reservation.',
    '_checkout.maintitle': 'Please enter the 6-digit PIN printed on your receipt.',
    '_checkout.noreservation': 'Your reservation is no longer valid. Please try with another PIN, or ask a staff member for assistance.',
    '_checkout.badpin': 'We don\'t recognize this PIN. Please try again!',
    '_overtime.next': 'GO TO PAYMENT',
    '_overtime.warning': 'Your locker won\'t open because you\'ve arrived after the appointed pick-up time.',
    '_overtime.info': 'To open your locker, please pay the indicated overtime fee.',
    '_payment.reservation.notfound': 'Due to a system error, we can\'t locate your reservation. Please contact a staff member for assistance. We apologize for the inconvenience.',
    '_overtime.overtime': 'Charged overtime',
    '_overtime.total': 'Overtime fee',
    '_overtime.locker.nr': 'Locker number:',
    '_thankyou.close': 'After you\'ve taken everything you need, please CLOSE your locker securely!',
    '_thankyou.visit': 'Please visit us again!',
    '_app.session.over': 'Your session will expire in',
    '_app.session.over.question': 'Would you like to continue the session?',
    '_app.session.continue': 'YES, CONTINUE',
    '_app.timout.time': 'seconds',
    '_app.session.stop': 'No, restart',
    '_app.no.availablelockers': 'We\'re sorry, but there are no lockers available at the moment. Please check back with us later. ',
    '_app.websocketdisconnect.nosession': 'Our automated terminal is temporarily out of service, so please ask a staff member for assistance. We apologize for the inconvenience.',
    '_app.websocketdisconnect.session': 'Our automated terminal is temporarily out of service, so please write down your Session ID (shown below) and ask a staff member for assistance. We apologize for the inconvenience.',
    '_checkinselect.rentlocker': 'Rent a locker now',
    '_checkinselect.reservation': 'Activate reservation',
    '_app.progress.pin': 'Enter PIN',
    '_checkout.info.reservation': 'Enter your PIN to activate your reservation and receive your locker number.',
    '_checkout.maintitle.reservation': 'Please enter the 6-digit PIN you recieved via the app and email.',
    '_app.errortitle': 'OOPS!',
    '_checkout.reservationerror': 'Your locker isn\'t ready to be opened yet. Please try again within 10 minutes of your reserved drop-off time.',
    '_app.ok': 'OK',
    '_review.paid': 'PAID',
    '_review.starttime': 'Drop-off time',
    '_review.summary.reservation': 'Your locker details',
    '_thankyou.reservation': 'You will also be able to check out with your 6-digit PIN! KEEP IT SAFE!',
    'en': 'English',
    'es': 'Spanish',
    'fr': 'French',
    'it': 'Italian',
    'ru': 'Russian',
    'zn': 'Chinese',
    '_language.title': 'Please select your preferred language.',
    '_app.help': 'Help',
    '_app.backmodaltitle': 'Are you sure?',
    '_app.backmodalbody': 'You will have to re-enter your data if you navigate back.',
    '_app.payment.begin_error': 'We couldn\'t start the payment.',
  };
  
  export default enMessages;