const huMessages = {
    '_thank_you': 'Köszönöm szépen',
    '_cancel': 'Mégsem',
    '_text_1': 'Helló mindenki, ez egy magyar mondat.',
    '_home.checkin.header': 'Check in',
    '_home.checkin.footer': 'Bérelj szekrényt a cuccaidnak',
    '_home.checkout.header': 'Check out',
    '_home.checkout.footer': 'Vedd ki a cuccaid és menj',
    '_app.back': 'Vissza',
    '_app.next': 'Következő',
    '_app.home': 'Kezdőlap',
    '_app.connection.error': 'Hálózati hiba lépett fel. Nem tudsz semmit se tenni.',
    '_app.backmodaltitle': 'Biztos vagy ebben?',
    '_app.backmodalbody': 'Majdnem minden eddig beállított adatot el fogsz veszíteni, ha visszalépsz.',
    '_checkin.size.title': 'MÉRET',
    '_checkin.time.title': 'IDŐ',
    '_checkin.time.1': 'óra',
    '_checkin.time.1.s': 'óra',
    '_checkin.time.2': 'hét',
    '_checkin.time.2.s': 'hét',
    '_checkin.time.3': 'perc',
    '_checkin.time.3.s': 'perc',
    '_checkin.time.4': 'nap',
    '_checkin.time.4.s': 'nap',
    '_checkin.endtime': 'Bérleti idő vége:',
    '_checkin.total': 'Összesen:',
    '_checkin.summary': 'ÖSSZEFOGLALÁS',
    '_checkin.size': 'Méret:',
    '_checkin.time': 'Idő:',
    '_app.progress.select': 'Kiválasztás',
    '_app.progress.review': 'Átnézés',
    '_app.progress.payment': 'Fizetés',
    '_app.progress.success': 'Siker',
    '_app.homemodalbody': 'Minden adatot el fogsz veszteni, ha a kezdőképernyőre navigálsz.',
    '_review.summary': 'SZEKRÉNYED RÉSZLETEI',
    '_review.info': 'INFÓ',
    '_review.acceptlabel': 'Itt elfogadom a',
    '_review.acceptlabel.2': 'Felhasználási feltételeket',
    '_review.checkboxmodal.title': 'Előrelépéshez el kell fogadnod a',
    '_app.creditcard.error': 'Valami gond van a bankkártya-olvasóval. Jelenleg nem tudod használni check in funkciót.',
    '_app.no_config_data': 'Nincsenek konfigurációs beállítások. Az oldal nem fog megfelelően működni, navigálj vissza.',
    '_checkin.changed.availabilities': 'Az általad választott szekrény - beállítások nem érvényesek többé. Kérlek, válassz mást!',
    '_app.no_session': 'Nincs session adat. Visszanavigálunk a kezdéshez.',
    '_app.no_required_data': 'Nincsenek meg a szükséges adatok. Visszanavigálunk a kezdéshez.',
    '_app.payment.begin_error': 'Nem tudtuk elindítani a fizetést.',
    '_app.retrybutton': 'Újra',
    '_review.backnavigate': 'Biztosan visszanavigálsz?',
    '_payment.failed': 'Nem sikerült a bankkártyás fizetés!',
    '_payment.success': 'Sikeres fizetés',
    '_payment.openlocker': 'Szekrény nyitás',
    '_payment.warning': 'Tartsd meg a bizonylatot, mert rajta van a szekrényed minden információja és a 6 számú PIN kódod, amire szükséged lesz, ha visszajössz a csomagjaidért.',
    '_payment.printing': 'Nyomtatás... Kérlek, várj!',
    '_payment.printing.ready': 'Kész! Kérlek vedd el a bizonylatot!',
    '_payment.locker': 'A szekrényszámod',
    '_payment.printer.fail': 'Nem tudunk nyomtatni! Kérlek írd fel a PIN kódot és a szekrényszámot!',
    '_payment.pin': 'PIN kód',
    '_payment.locker.number': 'Szekrény szám',
    '_thankyou.printfailed': 'Nem tudunk nyomtatni! Így nem kapsz bizonylatot a fizetésedről',
    '_thankyou.lockerfailed': 'A szekrény nem nyitható. Azonnal hívd az ügyfélszolgálatot vagy a személyzetet!',
    '_checkout.info': 'Ha most kijelentkezésnél kinyitod a szekrényt, nem tudod visszazárni egy újabb fizetés nélkül.',
    '_checkout.maintitle': 'Add meg a 6 jegyű PIN kódot, amit a kinyomtatott nyugtán találsz.',
    '_checkout.noreservation': 'A foglalásod nem érvényes. Próbáld egy másik PIN kóddal!',
    '_checkout.badpin': 'Nem ismerjük ezt a PIN kódot. Kérlek, próbáld újra!',
    '_overtime.next': 'Fizetés',
    '_overtime.warning': 'Rossz hír! Nem tudod kinyitni a szekrényt, mert a bérleti idő vége után jöttél vissza.',
    '_overtime.info': 'A szekrényed nyitásához fizesd ki a túlidő díjat.',
    '_payment.reservation.notfound': 'Nem találjuk a szekrény foglalást, amiért fizettél. Hívd az ügyfélszolgálatot!',
    '_overtime.overtime': 'Túlidő:',
    '_app.session.over': 'A munkafolyamatod lezárul',
    '_app.session.over.question': 'Akarod folytatni a munkafolyamatot?',
    '_app.session.continue': 'Igen, folytassuk',
    '_app.timout.time': 'másodpercen belül',
    '_app.session.stop': 'Ne, kezdjünk újat',
    '_app.no.availablelockers': 'Sajnáljuk, nincs elérhető szekrény, a check-in funkció nem elérhető.',
    '_app.websocketdisconnect': 'Végzetes hiba történt!',
    '_app.websocketdisconnect.nosession': 'Kérjük, hívd az ügyfélszolgálatot!',
    '_app.websocketdisconnect.session': 'Kérjük hívd az ügyfélszolgálatot az alábbi ügymenet-számmal!',
    'right': 'Jobbra találod',
    'left': 'Balra találod',
    'front': 'Szemben találod',
    'behind': 'Mögötted van',
    '_checkinselect.rentlocker': 'Rent a locker now',
    '_checkinselect.reservation': 'Activate reservation',
    '_app.progress.pin': 'Enter PIN',
    '_checkout.info.reservation': 'After you have identified your reservation with the PIN, you will get your locker number and can start to use the locker until the reservation end time.',
    '_checkout.maintitle.reservation': 'Please enter the 6 digit PIN that you reveived in the app and in email',
    '_review.starttime': 'Start time',
    '_review.paid': 'PAID',
    '_review.summary.reservation': 'Details of your reserved locker',
    '_success.lockernumber.text': 'You have locker nr.',
    '_review.overtime.info': 'In case you don\'t pick up your stuff until the END TIME you will have to pay overtime fee!',
    '_app.ok': 'OK',
    '_app.cancel': 'Cancel',
    '_app.errortitle': 'OOPS!',
    '_checkout.reservationerror': 'You cannot open the locker you have reserved yet. Try again not more than 10 minutes before your reservation start time!',
    '_overtime.total': 'Overtime fee',
    '_overtime.locker.nr': 'Locker nr.:',
    '_payment.title': 'Please make a payment!',
    '_payment.accept': 'We accept',
    '_payment.security': '100% SECURE PAYMENT',
    '_payment.processing': 'Processing...',
    '_thankyou.thankyou': 'Thank you!',
    '_thankyou.open': 'opened for you!',
    '_thankyou.keep': 'KEEP THE RECEIPT!',
    '_thankyou.keep.2': 'With your 6 digit PIN to open your locker!',
    '_thankyou.enjoy': 'Enjoy your time in',
    '_thankyou.next': 'Next customer',
    '_thankyou.close': 'Please CLOSE the door after you take everything',
    '_thankyou.visit': 'Visit us again!',
    '_thankyou.reservation': 'You will be able to check out with the same 6 digit PIN! KEEP IT SAFE!',
    'Budapest': 'Budapest',
    '_review.acceptlink': 'Read the Terms and Conditions',
    '_language.title': 'What is your preferred language?',
    '_app.help': 'Help',
    'en': 'Angol',
    'es': 'Spanyol',
    'fr': 'Francia',
    'it': 'Olasz',
    'ru': 'Orosz',
    'zn': 'Kínai',
    'de': 'Német',
    'hu': 'Magyar',
  };
  
  export default huMessages;